apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: name
  namespace: namespace
spec:
  interval: 1m
  chart:
    spec:
      chart: charts
      version: '0.1.0'
      sourceRef:
        kind: HelmRepository
        name: repo
        namespace: namespace
      interval: 1m
  values:
    test:
    images:
      tag: 13   # {"$imagepolicy": "poc:test-policy:tag"} 
    global:
      ingress:
        annotations:
        enabled: true
        hosts:
        - host: example.com
          paths:
          - path: /isAlive
            port: 3000
            service: test
        tls: []
